# Generated by Django 2.2.3 on 2019-07-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_logs', '0005_remove_alldata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldata',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
