# Generated by Django 2.2.3 on 2019-07-21 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_logs', '0006_auto_20190721_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file_logs.UploadFile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alldata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
